title: Stochastic determinism
description:
    Sporadic thoughts from me, which might as well have been synthesized
    by a Generative Adversial Network.
author: "Xitong Gao"
excerpt_separator: <!--more-->

plugins:
    - jekyll-feed
    - jekyll-assets

show_downloads: false
cayman-blog:
    # refer to http://shopify.github.io/liquid/filters/date/
    # if you want to customize this
    date_format: "%-d %b %Y"
theme: # leave it empty
