title: Stochastic determinism
description:
    Sporadic thoughts from me, which might as well have been synthesized
    by a Generative Adversial Network.
author: "Xitong Gao"

plugins:
    - jekyll-feed
    - jekyll-assets
    - jemoji

github:
    url: https://admk.github.io
excerpt_separator: <!--more-->
disqus_shortname: admk
